version: '2'
services:
    resume-mongodb:
        container_name: resume-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/resume/mongodb/:/data/db/
